// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xxwhlklgfaphssatiqgj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh4d2hsa2xnZmFwaHNzYXRpcWdqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU0MDI1NjksImV4cCI6MjA3MDk3ODU2OX0.jTFvKdfmqKMK0_6dXEEreJHm5NeCiEOx5Sgx8q7lCis";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});